// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axelar/evm/v1beta1/service.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("axelar/evm/v1beta1/service.proto", fileDescriptor_69cc2ee75499a0b3) }
func init() {
	golang_proto.RegisterFile("axelar/evm/v1beta1/service.proto", fileDescriptor_69cc2ee75499a0b3)
}

var fileDescriptor_69cc2ee75499a0b3 = []byte{
	// 1145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x97, 0xbd, 0x6f, 0x1c, 0x45,
	0x14, 0xc0, 0x33, 0x08, 0xa2, 0x68, 0xb0, 0x92, 0x30, 0x22, 0x44, 0x9c, 0xa3, 0xb3, 0xbd, 0xb1,
	0xe3, 0xd8, 0xce, 0xdd, 0xc6, 0x36, 0x1f, 0x22, 0x5d, 0xec, 0xf0, 0xa5, 0xf0, 0x19, 0x47, 0x14,
	0x34, 0xa7, 0xbd, 0xdd, 0xe7, 0xbd, 0xd5, 0xdd, 0xcd, 0x5c, 0x76, 0xc6, 0x67, 0xaf, 0x22, 0x0b,
	0x29, 0x42, 0xa2, 0x89, 0x00, 0x89, 0x86, 0x22, 0x45, 0x1a, 0x3a, 0x0a, 0x0a, 0xfe, 0x80, 0x94,
	0x94, 0x91, 0x28, 0xa0, 0x44, 0x36, 0xff, 0x04, 0x1d, 0xda, 0xd9, 0x99, 0xdb, 0x8f, 0x1b, 0x4f,
	0xd6, 0x9d, 0xad, 0xf9, 0xbd, 0x79, 0xbf, 0xdb, 0x7d, 0xef, 0xcd, 0x2c, 0x9e, 0xf7, 0x0e, 0x60,
	0xe0, 0xc5, 0x2e, 0x8c, 0x87, 0xee, 0x78, 0xbd, 0x0b, 0xc2, 0x5b, 0x77, 0x39, 0xc4, 0xe3, 0xc8,
	0x87, 0xf6, 0x28, 0x66, 0x82, 0x11, 0x92, 0x11, 0x6d, 0x18, 0x0f, 0xdb, 0x8a, 0x68, 0xbc, 0x1e,
	0xb2, 0x90, 0xc9, 0x65, 0x37, 0xfd, 0x2b, 0x23, 0x1b, 0x57, 0x42, 0xc6, 0xc2, 0x01, 0xb8, 0xde,
	0x28, 0x72, 0x3d, 0x4a, 0x99, 0xf0, 0x44, 0xc4, 0x28, 0x57, 0xab, 0xb3, 0x86, 0x4c, 0xe2, 0x40,
	0x2d, 0x36, 0x0d, 0x8b, 0x0f, 0xf6, 0x20, 0x4e, 0xb2, 0xf5, 0x8d, 0xff, 0x08, 0xc6, 0x9f, 0xf2,
	0x70, 0x27, 0x33, 0x23, 0xdf, 0x60, 0xbc, 0x03, 0xe2, 0x43, 0x4f, 0xc0, 0xbe, 0x97, 0x90, 0xa5,
	0xf6, 0xb4, 0x62, 0x3b, 0x5f, 0xbf, 0x07, 0x0f, 0xf6, 0x80, 0x8b, 0xc6, 0xb5, 0x17, 0x61, 0x7c,
	0xc4, 0x28, 0x07, 0xc7, 0x79, 0xf4, 0xe7, 0xbf, 0x3f, 0xbd, 0x74, 0xc5, 0xb9, 0xec, 0x16, 0xa4,
	0x38, 0x88, 0x4e, 0x98, 0x81, 0xb7, 0xd0, 0x2a, 0xf9, 0x19, 0xe1, 0x8b, 0xdb, 0x8c, 0xee, 0x46,
	0xf1, 0x50, 0x85, 0xdf, 0x3f, 0x20, 0x6b, 0xa6, 0x04, 0x55, 0x4a, 0xdb, 0xdc, 0xa8, 0x07, 0x2b,
	0xa7, 0x15, 0xe9, 0x74, 0xd5, 0x69, 0x16, 0x9d, 0xfc, 0x8c, 0xd6, 0x5e, 0x1d, 0x71, 0x90, 0xaa,
	0xed, 0xe2, 0x97, 0x3f, 0x89, 0x68, 0x9f, 0xcc, 0x99, 0x12, 0xa4, 0x2b, 0xda, 0x60, 0xfe, 0x64,
	0x40, 0x65, 0x9d, 0x95, 0x59, 0x2f, 0x39, 0x17, 0x8b, 0x59, 0x07, 0x11, 0xed, 0xa7, 0x79, 0xbe,
	0x43, 0x78, 0x46, 0xf9, 0x6e, 0xf7, 0xbc, 0x88, 0x92, 0x65, 0xcb, 0x2f, 0x92, 0x84, 0x4e, 0x7c,
	0xfd, 0xc5, 0xa0, 0x12, 0x58, 0x94, 0x02, 0x4d, 0xe7, 0x4d, 0xd3, 0xcf, 0xf6, 0x53, 0xb4, 0x62,
	0x72, 0x9f, 0xf5, 0xc1, 0x6e, 0x22, 0x89, 0x3a, 0x26, 0x0a, 0xac, 0x63, 0x22, 0x52, 0x34, 0x35,
	0xf9, 0x01, 0xe1, 0xf3, 0x2a, 0xfc, 0x0e, 0x8c, 0x18, 0x8f, 0x04, 0x59, 0xb1, 0xa4, 0x50, 0x8c,
	0xb6, 0x59, 0xad, 0x83, 0x2a, 0x9f, 0x6b, 0xd2, 0x67, 0xde, 0x99, 0x35, 0xf9, 0x04, 0x19, 0x9c,
	0x1a, 0x3d, 0x45, 0x98, 0xe8, 0x1f, 0x14, 0x7b, 0x94, 0xef, 0x42, 0x7c, 0x17, 0x12, 0xd2, 0xb2,
	0xfd, 0xf0, 0x9c, 0xd3, 0x66, 0xed, 0xba, 0xb8, 0xb2, 0x5b, 0x93, 0x76, 0x4b, 0xce, 0xbc, 0xf1,
	0x69, 0xa9, 0x80, 0x4e, 0x1f, 0x26, 0xbd, 0xf4, 0x15, 0x13, 0x50, 0x2a, 0x26, 0x63, 0x2f, 0x55,
	0x29, 0x6b, 0x2f, 0x4d, 0xc3, 0xb6, 0x5e, 0x1a, 0x33, 0x01, 0x9d, 0xa9, 0xca, 0x7a, 0x82, 0xf0,
	0x6b, 0xdb, 0x31, 0x78, 0x02, 0xee, 0xc0, 0x68, 0xc0, 0x92, 0xac, 0xbc, 0xcc, 0xad, 0x5b, 0xc5,
	0xb4, 0x5c, 0xab, 0x26, 0xad, 0xec, 0x56, 0xa5, 0xdd, 0xa2, 0x33, 0x57, 0x7a, 0x74, 0x12, 0x4f,
	0xdf, 0xeb, 0x80, 0x25, 0x79, 0xb9, 0xc9, 0x29, 0x24, 0x97, 0xb6, 0xf6, 0x62, 0x2a, 0xf7, 0xe1,
	0x27, 0x4c, 0xa1, 0x0a, 0x65, 0x9f, 0x42, 0x53, 0xb0, 0x75, 0x0a, 0x65, 0x6e, 0xdd, 0xbd, 0x98,
	0x66, 0x66, 0x3c, 0x55, 0xfb, 0x0d, 0xe1, 0x37, 0xb2, 0x7d, 0xbe, 0x00, 0x1a, 0x44, 0x34, 0xd4,
	0x65, 0xc2, 0xc9, 0xfa, 0xc9, 0x39, 0xab, 0xac, 0xd6, 0xdc, 0x38, 0x4d, 0x88, 0x92, 0x75, 0xa5,
	0xec, 0x8a, 0xb3, 0x68, 0x90, 0x1d, 0x65, 0x41, 0x93, 0x52, 0x94, 0xca, 0xbf, 0x23, 0x7c, 0x39,
	0xdb, 0x53, 0x6f, 0xf6, 0xf9, 0x3e, 0x85, 0x98, 0xf7, 0xa2, 0x11, 0xb1, 0x08, 0x4c, 0xc1, 0x5a,
	0x7a, 0xf3, 0x54, 0x31, 0xca, 0xfa, 0xa6, 0xb4, 0x5e, 0x75, 0x96, 0x0c, 0xd6, 0x93, 0xc6, 0x61,
	0x3a, 0x2c, 0xd5, 0x7e, 0x86, 0x70, 0xa3, 0xb2, 0xeb, 0x08, 0x62, 0x4f, 0xb0, 0xcc, 0xfc, 0xed,
	0x1a, 0x16, 0x05, 0x5e, 0xcb, 0xbf, 0x73, 0xda, 0x30, 0xe5, 0xbf, 0x29, 0xfd, 0x5b, 0xce, 0x75,
	0xab, 0x7f, 0x21, 0x52, 0x0f, 0xf0, 0x9d, 0x28, 0xa4, 0xdb, 0x6c, 0x38, 0xf4, 0x68, 0xc0, 0xcd,
	0x03, 0xbc, 0x48, 0x58, 0x07, 0x78, 0x19, 0xb4, 0x0d, 0x70, 0x1e, 0x85, 0xb4, 0xe3, 0x2b, 0x34,
	0x35, 0xd9, 0xc7, 0xe7, 0x6e, 0x07, 0x41, 0x36, 0x82, 0xae, 0x9a, 0xf6, 0xd6, 0xab, 0x5a, 0x60,
	0xd1, 0x0e, 0xa9, 0xe4, 0xf3, 0x32, 0x79, 0xc3, 0xb9, 0x54, 0x4c, 0xee, 0x05, 0x41, 0x3e, 0x69,
	0xd2, 0x56, 0xbe, 0x07, 0x22, 0x4e, 0x3e, 0xf0, 0xa2, 0x01, 0x04, 0xef, 0x8f, 0x81, 0x0a, 0x73,
	0x2b, 0x57, 0x29, 0x6b, 0x2b, 0x4f, 0xc3, 0xb6, 0x56, 0x8e, 0x53, 0xba, 0xb5, 0x2b, 0xf1, 0x16,
	0xa4, 0xfc, 0x2d, 0xb4, 0xba, 0xf1, 0xd7, 0xab, 0x78, 0xe6, 0xcb, 0xf4, 0x2e, 0xa6, 0x6f, 0x5f,
	0xbf, 0x20, 0x7c, 0x61, 0xcb, 0x13, 0x7e, 0x0f, 0x82, 0xc9, 0x1b, 0x33, 0x9e, 0x5d, 0x15, 0x48,
	0x9b, 0xae, 0xd5, 0x62, 0x95, 0xe8, 0x7b, 0x52, 0x74, 0x93, 0xac, 0xbb, 0x86, 0x2b, 0x62, 0x37,
	0x0b, 0x9a, 0xbc, 0x42, 0xf7, 0xa1, 0x7c, 0xa0, 0x87, 0xee, 0xc3, 0x28, 0x38, 0x24, 0xdf, 0x22,
	0x8c, 0xd3, 0x29, 0x06, 0xf1, 0xc7, 0x74, 0x97, 0x99, 0xaf, 0x89, 0xf9, 0xba, 0xf5, 0x9a, 0x58,
	0xc4, 0x94, 0xd8, 0xb2, 0x14, 0x5b, 0x20, 0x73, 0x46, 0x31, 0xc9, 0x77, 0xa2, 0x34, 0xef, 0xaf,
	0xf9, 0x11, 0x2c, 0x2f, 0xc4, 0x1f, 0x41, 0x14, 0xf6, 0x84, 0xf5, 0x08, 0x2e, 0x70, 0x75, 0x8e,
	0xe0, 0x12, 0xae, 0xf4, 0xde, 0x95, 0x7a, 0xeb, 0xc4, 0x35, 0xe9, 0xf9, 0x85, 0xb8, 0x4e, 0x4f,
	0x06, 0xea, 0x47, 0x47, 0x1e, 0x23, 0x3c, 0xa3, 0x6e, 0x1b, 0x3b, 0xc2, 0x13, 0x60, 0x6e, 0xc6,
	0x22, 0x61, 0x6d, 0xc6, 0x32, 0x58, 0xae, 0x3e, 0xb2, 0x60, 0x92, 0x53, 0xb7, 0x97, 0x0e, 0x97,
	0xd9, 0x9f, 0x22, 0x7c, 0x41, 0xcd, 0x78, 0x7b, 0xb1, 0x55, 0x20, 0x6b, 0xb1, 0x4d, 0xb1, 0xca,
	0xeb, 0x2d, 0xe9, 0xd5, 0x26, 0x37, 0x4c, 0x5e, 0xfa, 0xd0, 0xa8, 0x16, 0x1b, 0xe1, 0xf8, 0xac,
	0x6c, 0x77, 0x4e, 0x16, 0x8c, 0x2f, 0x49, 0xae, 0x69, 0x1f, 0xc7, 0x86, 0x94, 0xbf, 0x40, 0x48,
	0xc3, 0xf8, 0xee, 0xb2, 0x54, 0x8f, 0x11, 0xc6, 0x77, 0x21, 0xb9, 0x1d, 0x04, 0x31, 0x70, 0x6e,
	0x2e, 0xee, 0x7c, 0xdd, 0x5a, 0xdc, 0x45, 0xac, 0x7c, 0x78, 0x92, 0x65, 0x93, 0x41, 0x1f, 0x92,
	0x8e, 0x97, 0x05, 0x4c, 0x9e, 0xc1, 0x13, 0x84, 0xcf, 0xab, 0xcf, 0x16, 0xad, 0x64, 0xbc, 0xf9,
	0x96, 0x19, 0xeb, 0xcd, 0xb7, 0x8a, 0x96, 0x4f, 0x18, 0xb2, 0x66, 0x52, 0xd3, 0x9f, 0x42, 0x55,
	0xbd, 0xef, 0x11, 0x3e, 0xb7, 0x95, 0x08, 0xf0, 0x59, 0x00, 0xe6, 0xc1, 0xae, 0x57, 0xad, 0x83,
	0x3d, 0x87, 0xea, 0x74, 0x59, 0x57, 0xd1, 0xf9, 0x54, 0xf2, 0x19, 0x15, 0xb1, 0xe7, 0x8b, 0x43,
	0xf2, 0x08, 0xe1, 0x57, 0xb2, 0x21, 0x6f, 0xfc, 0x0c, 0x2b, 0x4d, 0xf6, 0x05, 0x0b, 0x51, 0xa7,
	0x70, 0xe5, 0x24, 0xcf, 0x25, 0xe4, 0xbf, 0x9d, 0x28, 0x38, 0xdc, 0xfa, 0xec, 0x8f, 0xa3, 0x26,
	0x7a, 0x7e, 0xd4, 0x44, 0xff, 0x1c, 0x35, 0xd1, 0x8f, 0xc7, 0xcd, 0x33, 0xcf, 0x8e, 0x9b, 0xe8,
	0xf9, 0x71, 0xf3, 0xcc, 0xdf, 0xc7, 0xcd, 0x33, 0x5f, 0xdf, 0x0c, 0x23, 0xd1, 0xdb, 0xeb, 0xb6,
	0x7d, 0x36, 0x54, 0xbb, 0x52, 0x10, 0xfb, 0x2c, 0xee, 0xab, 0xff, 0x5a, 0x3e, 0x8b, 0xc1, 0x3d,
	0x90, 0xa9, 0x44, 0x32, 0x02, 0xde, 0x3d, 0x2b, 0x3f, 0xd6, 0x37, 0xff, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x48, 0xb7, 0x49, 0xbc, 0x55, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgServiceClient interface {
	SetGateway(ctx context.Context, in *SetGatewayRequest, opts ...grpc.CallOption) (*SetGatewayResponse, error)
	ConfirmGatewayTx(ctx context.Context, in *ConfirmGatewayTxRequest, opts ...grpc.CallOption) (*ConfirmGatewayTxResponse, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	ConfirmChain(ctx context.Context, in *ConfirmChainRequest, opts ...grpc.CallOption) (*ConfirmChainResponse, error)
	ConfirmToken(ctx context.Context, in *ConfirmTokenRequest, opts ...grpc.CallOption) (*ConfirmTokenResponse, error)
	ConfirmDeposit(ctx context.Context, in *ConfirmDepositRequest, opts ...grpc.CallOption) (*ConfirmDepositResponse, error)
	ConfirmTransferKey(ctx context.Context, in *ConfirmTransferKeyRequest, opts ...grpc.CallOption) (*ConfirmTransferKeyResponse, error)
	VoteConfirmChain(ctx context.Context, in *VoteConfirmChainRequest, opts ...grpc.CallOption) (*VoteConfirmChainResponse, error)
	CreateDeployToken(ctx context.Context, in *CreateDeployTokenRequest, opts ...grpc.CallOption) (*CreateDeployTokenResponse, error)
	CreateBurnTokens(ctx context.Context, in *CreateBurnTokensRequest, opts ...grpc.CallOption) (*CreateBurnTokensResponse, error)
	CreatePendingTransfers(ctx context.Context, in *CreatePendingTransfersRequest, opts ...grpc.CallOption) (*CreatePendingTransfersResponse, error)
	CreateTransferOwnership(ctx context.Context, in *CreateTransferOwnershipRequest, opts ...grpc.CallOption) (*CreateTransferOwnershipResponse, error)
	CreateTransferOperatorship(ctx context.Context, in *CreateTransferOperatorshipRequest, opts ...grpc.CallOption) (*CreateTransferOperatorshipResponse, error)
	SignCommands(ctx context.Context, in *SignCommandsRequest, opts ...grpc.CallOption) (*SignCommandsResponse, error)
	AddChain(ctx context.Context, in *AddChainRequest, opts ...grpc.CallOption) (*AddChainResponse, error)
	RetryFailedEvent(ctx context.Context, in *RetryFailedEventRequest, opts ...grpc.CallOption) (*RetryFailedEventResponse, error)
}

type msgServiceClient struct {
	cc grpc1.ClientConn
}

func NewMsgServiceClient(cc grpc1.ClientConn) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) SetGateway(ctx context.Context, in *SetGatewayRequest, opts ...grpc.CallOption) (*SetGatewayResponse, error) {
	out := new(SetGatewayResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/SetGateway", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmGatewayTx(ctx context.Context, in *ConfirmGatewayTxRequest, opts ...grpc.CallOption) (*ConfirmGatewayTxResponse, error) {
	out := new(ConfirmGatewayTxResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/ConfirmGatewayTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/Link", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmChain(ctx context.Context, in *ConfirmChainRequest, opts ...grpc.CallOption) (*ConfirmChainResponse, error) {
	out := new(ConfirmChainResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/ConfirmChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmToken(ctx context.Context, in *ConfirmTokenRequest, opts ...grpc.CallOption) (*ConfirmTokenResponse, error) {
	out := new(ConfirmTokenResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/ConfirmToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmDeposit(ctx context.Context, in *ConfirmDepositRequest, opts ...grpc.CallOption) (*ConfirmDepositResponse, error) {
	out := new(ConfirmDepositResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/ConfirmDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmTransferKey(ctx context.Context, in *ConfirmTransferKeyRequest, opts ...grpc.CallOption) (*ConfirmTransferKeyResponse, error) {
	out := new(ConfirmTransferKeyResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/ConfirmTransferKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) VoteConfirmChain(ctx context.Context, in *VoteConfirmChainRequest, opts ...grpc.CallOption) (*VoteConfirmChainResponse, error) {
	out := new(VoteConfirmChainResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/VoteConfirmChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateDeployToken(ctx context.Context, in *CreateDeployTokenRequest, opts ...grpc.CallOption) (*CreateDeployTokenResponse, error) {
	out := new(CreateDeployTokenResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/CreateDeployToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateBurnTokens(ctx context.Context, in *CreateBurnTokensRequest, opts ...grpc.CallOption) (*CreateBurnTokensResponse, error) {
	out := new(CreateBurnTokensResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/CreateBurnTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreatePendingTransfers(ctx context.Context, in *CreatePendingTransfersRequest, opts ...grpc.CallOption) (*CreatePendingTransfersResponse, error) {
	out := new(CreatePendingTransfersResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/CreatePendingTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateTransferOwnership(ctx context.Context, in *CreateTransferOwnershipRequest, opts ...grpc.CallOption) (*CreateTransferOwnershipResponse, error) {
	out := new(CreateTransferOwnershipResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/CreateTransferOwnership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateTransferOperatorship(ctx context.Context, in *CreateTransferOperatorshipRequest, opts ...grpc.CallOption) (*CreateTransferOperatorshipResponse, error) {
	out := new(CreateTransferOperatorshipResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/CreateTransferOperatorship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SignCommands(ctx context.Context, in *SignCommandsRequest, opts ...grpc.CallOption) (*SignCommandsResponse, error) {
	out := new(SignCommandsResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/SignCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) AddChain(ctx context.Context, in *AddChainRequest, opts ...grpc.CallOption) (*AddChainResponse, error) {
	out := new(AddChainResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/AddChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) RetryFailedEvent(ctx context.Context, in *RetryFailedEventRequest, opts ...grpc.CallOption) (*RetryFailedEventResponse, error) {
	out := new(RetryFailedEventResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.MsgService/RetryFailedEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
type MsgServiceServer interface {
	SetGateway(context.Context, *SetGatewayRequest) (*SetGatewayResponse, error)
	ConfirmGatewayTx(context.Context, *ConfirmGatewayTxRequest) (*ConfirmGatewayTxResponse, error)
	Link(context.Context, *LinkRequest) (*LinkResponse, error)
	ConfirmChain(context.Context, *ConfirmChainRequest) (*ConfirmChainResponse, error)
	ConfirmToken(context.Context, *ConfirmTokenRequest) (*ConfirmTokenResponse, error)
	ConfirmDeposit(context.Context, *ConfirmDepositRequest) (*ConfirmDepositResponse, error)
	ConfirmTransferKey(context.Context, *ConfirmTransferKeyRequest) (*ConfirmTransferKeyResponse, error)
	VoteConfirmChain(context.Context, *VoteConfirmChainRequest) (*VoteConfirmChainResponse, error)
	CreateDeployToken(context.Context, *CreateDeployTokenRequest) (*CreateDeployTokenResponse, error)
	CreateBurnTokens(context.Context, *CreateBurnTokensRequest) (*CreateBurnTokensResponse, error)
	CreatePendingTransfers(context.Context, *CreatePendingTransfersRequest) (*CreatePendingTransfersResponse, error)
	CreateTransferOwnership(context.Context, *CreateTransferOwnershipRequest) (*CreateTransferOwnershipResponse, error)
	CreateTransferOperatorship(context.Context, *CreateTransferOperatorshipRequest) (*CreateTransferOperatorshipResponse, error)
	SignCommands(context.Context, *SignCommandsRequest) (*SignCommandsResponse, error)
	AddChain(context.Context, *AddChainRequest) (*AddChainResponse, error)
	RetryFailedEvent(context.Context, *RetryFailedEventRequest) (*RetryFailedEventResponse, error)
}

// UnimplementedMsgServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (*UnimplementedMsgServiceServer) SetGateway(ctx context.Context, req *SetGatewayRequest) (*SetGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGateway not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmGatewayTx(ctx context.Context, req *ConfirmGatewayTxRequest) (*ConfirmGatewayTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmGatewayTx not implemented")
}
func (*UnimplementedMsgServiceServer) Link(ctx context.Context, req *LinkRequest) (*LinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Link not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmChain(ctx context.Context, req *ConfirmChainRequest) (*ConfirmChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmChain not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmToken(ctx context.Context, req *ConfirmTokenRequest) (*ConfirmTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmToken not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmDeposit(ctx context.Context, req *ConfirmDepositRequest) (*ConfirmDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmDeposit not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmTransferKey(ctx context.Context, req *ConfirmTransferKeyRequest) (*ConfirmTransferKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTransferKey not implemented")
}
func (*UnimplementedMsgServiceServer) VoteConfirmChain(ctx context.Context, req *VoteConfirmChainRequest) (*VoteConfirmChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteConfirmChain not implemented")
}
func (*UnimplementedMsgServiceServer) CreateDeployToken(ctx context.Context, req *CreateDeployTokenRequest) (*CreateDeployTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployToken not implemented")
}
func (*UnimplementedMsgServiceServer) CreateBurnTokens(ctx context.Context, req *CreateBurnTokensRequest) (*CreateBurnTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBurnTokens not implemented")
}
func (*UnimplementedMsgServiceServer) CreatePendingTransfers(ctx context.Context, req *CreatePendingTransfersRequest) (*CreatePendingTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePendingTransfers not implemented")
}
func (*UnimplementedMsgServiceServer) CreateTransferOwnership(ctx context.Context, req *CreateTransferOwnershipRequest) (*CreateTransferOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransferOwnership not implemented")
}
func (*UnimplementedMsgServiceServer) CreateTransferOperatorship(ctx context.Context, req *CreateTransferOperatorshipRequest) (*CreateTransferOperatorshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransferOperatorship not implemented")
}
func (*UnimplementedMsgServiceServer) SignCommands(ctx context.Context, req *SignCommandsRequest) (*SignCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignCommands not implemented")
}
func (*UnimplementedMsgServiceServer) AddChain(ctx context.Context, req *AddChainRequest) (*AddChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChain not implemented")
}
func (*UnimplementedMsgServiceServer) RetryFailedEvent(ctx context.Context, req *RetryFailedEventRequest) (*RetryFailedEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryFailedEvent not implemented")
}

func RegisterMsgServiceServer(s grpc1.Server, srv MsgServiceServer) {
	s.RegisterService(&_MsgService_serviceDesc, srv)
}

func _MsgService_SetGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SetGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/SetGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SetGateway(ctx, req.(*SetGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmGatewayTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmGatewayTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmGatewayTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/ConfirmGatewayTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmGatewayTx(ctx, req.(*ConfirmGatewayTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/ConfirmChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmChain(ctx, req.(*ConfirmChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/ConfirmToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmToken(ctx, req.(*ConfirmTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/ConfirmDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmDeposit(ctx, req.(*ConfirmDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmTransferKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransferKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmTransferKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/ConfirmTransferKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmTransferKey(ctx, req.(*ConfirmTransferKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_VoteConfirmChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteConfirmChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).VoteConfirmChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/VoteConfirmChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).VoteConfirmChain(ctx, req.(*VoteConfirmChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateDeployToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeployTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateDeployToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/CreateDeployToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateDeployToken(ctx, req.(*CreateDeployTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateBurnTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBurnTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateBurnTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/CreateBurnTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateBurnTokens(ctx, req.(*CreateBurnTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreatePendingTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePendingTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreatePendingTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/CreatePendingTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreatePendingTransfers(ctx, req.(*CreatePendingTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateTransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateTransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/CreateTransferOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateTransferOwnership(ctx, req.(*CreateTransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateTransferOperatorship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferOperatorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateTransferOperatorship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/CreateTransferOperatorship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateTransferOperatorship(ctx, req.(*CreateTransferOperatorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SignCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SignCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/SignCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SignCommands(ctx, req.(*SignCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_AddChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).AddChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/AddChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).AddChain(ctx, req.(*AddChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_RetryFailedEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFailedEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).RetryFailedEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.MsgService/RetryFailedEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).RetryFailedEvent(ctx, req.(*RetryFailedEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "axelar.evm.v1beta1.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetGateway",
			Handler:    _MsgService_SetGateway_Handler,
		},
		{
			MethodName: "ConfirmGatewayTx",
			Handler:    _MsgService_ConfirmGatewayTx_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _MsgService_Link_Handler,
		},
		{
			MethodName: "ConfirmChain",
			Handler:    _MsgService_ConfirmChain_Handler,
		},
		{
			MethodName: "ConfirmToken",
			Handler:    _MsgService_ConfirmToken_Handler,
		},
		{
			MethodName: "ConfirmDeposit",
			Handler:    _MsgService_ConfirmDeposit_Handler,
		},
		{
			MethodName: "ConfirmTransferKey",
			Handler:    _MsgService_ConfirmTransferKey_Handler,
		},
		{
			MethodName: "VoteConfirmChain",
			Handler:    _MsgService_VoteConfirmChain_Handler,
		},
		{
			MethodName: "CreateDeployToken",
			Handler:    _MsgService_CreateDeployToken_Handler,
		},
		{
			MethodName: "CreateBurnTokens",
			Handler:    _MsgService_CreateBurnTokens_Handler,
		},
		{
			MethodName: "CreatePendingTransfers",
			Handler:    _MsgService_CreatePendingTransfers_Handler,
		},
		{
			MethodName: "CreateTransferOwnership",
			Handler:    _MsgService_CreateTransferOwnership_Handler,
		},
		{
			MethodName: "CreateTransferOperatorship",
			Handler:    _MsgService_CreateTransferOperatorship_Handler,
		},
		{
			MethodName: "SignCommands",
			Handler:    _MsgService_SignCommands_Handler,
		},
		{
			MethodName: "AddChain",
			Handler:    _MsgService_AddChain_Handler,
		},
		{
			MethodName: "RetryFailedEvent",
			Handler:    _MsgService_RetryFailedEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "axelar/evm/v1beta1/service.proto",
}

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryServiceClient interface {
	// BatchedCommands queries the batched commands for a specified chain and
	// BatchedCommandsID if no BatchedCommandsID is specified, then it returns the
	// latest batched commands
	BatchedCommands(ctx context.Context, in *BatchedCommandsRequest, opts ...grpc.CallOption) (*BatchedCommandsResponse, error)
	// BurnerInfo queries the burner info for the specified address
	BurnerInfo(ctx context.Context, in *BurnerInfoRequest, opts ...grpc.CallOption) (*BurnerInfoResponse, error)
	// ConfirmationHeight queries the confirmation height for the specified chain
	ConfirmationHeight(ctx context.Context, in *ConfirmationHeightRequest, opts ...grpc.CallOption) (*ConfirmationHeightResponse, error)
	// DepositState queries the state of the specified deposit
	DepositState(ctx context.Context, in *DepositStateRequest, opts ...grpc.CallOption) (*DepositStateResponse, error)
	// PendingCommands queries the pending commands for the specified chain
	PendingCommands(ctx context.Context, in *PendingCommandsRequest, opts ...grpc.CallOption) (*PendingCommandsResponse, error)
	// Chains queries the available evm chains
	Chains(ctx context.Context, in *ChainsRequest, opts ...grpc.CallOption) (*ChainsResponse, error)
	// KeyAddress queries the address of key of a chain
	KeyAddress(ctx context.Context, in *KeyAddressRequest, opts ...grpc.CallOption) (*KeyAddressResponse, error)
	// GatewayAddress queries the address of axelar gateway at the specified chain
	GatewayAddress(ctx context.Context, in *GatewayAddressRequest, opts ...grpc.CallOption) (*GatewayAddressResponse, error)
	// Bytecode queries the bytecode of a specified gateway at the specified chain
	Bytecode(ctx context.Context, in *BytecodeRequest, opts ...grpc.CallOption) (*BytecodeResponse, error)
	// Event queries an event at the specified chain
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type queryServiceClient struct {
	cc grpc1.ClientConn
}

func NewQueryServiceClient(cc grpc1.ClientConn) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) BatchedCommands(ctx context.Context, in *BatchedCommandsRequest, opts ...grpc.CallOption) (*BatchedCommandsResponse, error) {
	out := new(BatchedCommandsResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/BatchedCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) BurnerInfo(ctx context.Context, in *BurnerInfoRequest, opts ...grpc.CallOption) (*BurnerInfoResponse, error) {
	out := new(BurnerInfoResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/BurnerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ConfirmationHeight(ctx context.Context, in *ConfirmationHeightRequest, opts ...grpc.CallOption) (*ConfirmationHeightResponse, error) {
	out := new(ConfirmationHeightResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/ConfirmationHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) DepositState(ctx context.Context, in *DepositStateRequest, opts ...grpc.CallOption) (*DepositStateResponse, error) {
	out := new(DepositStateResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/DepositState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) PendingCommands(ctx context.Context, in *PendingCommandsRequest, opts ...grpc.CallOption) (*PendingCommandsResponse, error) {
	out := new(PendingCommandsResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/PendingCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Chains(ctx context.Context, in *ChainsRequest, opts ...grpc.CallOption) (*ChainsResponse, error) {
	out := new(ChainsResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/Chains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) KeyAddress(ctx context.Context, in *KeyAddressRequest, opts ...grpc.CallOption) (*KeyAddressResponse, error) {
	out := new(KeyAddressResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/KeyAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GatewayAddress(ctx context.Context, in *GatewayAddressRequest, opts ...grpc.CallOption) (*GatewayAddressResponse, error) {
	out := new(GatewayAddressResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/GatewayAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Bytecode(ctx context.Context, in *BytecodeRequest, opts ...grpc.CallOption) (*BytecodeResponse, error) {
	out := new(BytecodeResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/Bytecode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/axelar.evm.v1beta1.QueryService/Event", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
type QueryServiceServer interface {
	// BatchedCommands queries the batched commands for a specified chain and
	// BatchedCommandsID if no BatchedCommandsID is specified, then it returns the
	// latest batched commands
	BatchedCommands(context.Context, *BatchedCommandsRequest) (*BatchedCommandsResponse, error)
	// BurnerInfo queries the burner info for the specified address
	BurnerInfo(context.Context, *BurnerInfoRequest) (*BurnerInfoResponse, error)
	// ConfirmationHeight queries the confirmation height for the specified chain
	ConfirmationHeight(context.Context, *ConfirmationHeightRequest) (*ConfirmationHeightResponse, error)
	// DepositState queries the state of the specified deposit
	DepositState(context.Context, *DepositStateRequest) (*DepositStateResponse, error)
	// PendingCommands queries the pending commands for the specified chain
	PendingCommands(context.Context, *PendingCommandsRequest) (*PendingCommandsResponse, error)
	// Chains queries the available evm chains
	Chains(context.Context, *ChainsRequest) (*ChainsResponse, error)
	// KeyAddress queries the address of key of a chain
	KeyAddress(context.Context, *KeyAddressRequest) (*KeyAddressResponse, error)
	// GatewayAddress queries the address of axelar gateway at the specified chain
	GatewayAddress(context.Context, *GatewayAddressRequest) (*GatewayAddressResponse, error)
	// Bytecode queries the bytecode of a specified gateway at the specified chain
	Bytecode(context.Context, *BytecodeRequest) (*BytecodeResponse, error)
	// Event queries an event at the specified chain
	Event(context.Context, *EventRequest) (*EventResponse, error)
}

// UnimplementedQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (*UnimplementedQueryServiceServer) BatchedCommands(ctx context.Context, req *BatchedCommandsRequest) (*BatchedCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchedCommands not implemented")
}
func (*UnimplementedQueryServiceServer) BurnerInfo(ctx context.Context, req *BurnerInfoRequest) (*BurnerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnerInfo not implemented")
}
func (*UnimplementedQueryServiceServer) ConfirmationHeight(ctx context.Context, req *ConfirmationHeightRequest) (*ConfirmationHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmationHeight not implemented")
}
func (*UnimplementedQueryServiceServer) DepositState(ctx context.Context, req *DepositStateRequest) (*DepositStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositState not implemented")
}
func (*UnimplementedQueryServiceServer) PendingCommands(ctx context.Context, req *PendingCommandsRequest) (*PendingCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingCommands not implemented")
}
func (*UnimplementedQueryServiceServer) Chains(ctx context.Context, req *ChainsRequest) (*ChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chains not implemented")
}
func (*UnimplementedQueryServiceServer) KeyAddress(ctx context.Context, req *KeyAddressRequest) (*KeyAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyAddress not implemented")
}
func (*UnimplementedQueryServiceServer) GatewayAddress(ctx context.Context, req *GatewayAddressRequest) (*GatewayAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayAddress not implemented")
}
func (*UnimplementedQueryServiceServer) Bytecode(ctx context.Context, req *BytecodeRequest) (*BytecodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bytecode not implemented")
}
func (*UnimplementedQueryServiceServer) Event(ctx context.Context, req *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}

func RegisterQueryServiceServer(s grpc1.Server, srv QueryServiceServer) {
	s.RegisterService(&_QueryService_serviceDesc, srv)
}

func _QueryService_BatchedCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchedCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).BatchedCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/BatchedCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).BatchedCommands(ctx, req.(*BatchedCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_BurnerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BurnerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).BurnerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/BurnerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).BurnerInfo(ctx, req.(*BurnerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ConfirmationHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ConfirmationHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/ConfirmationHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ConfirmationHeight(ctx, req.(*ConfirmationHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_DepositState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).DepositState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/DepositState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).DepositState(ctx, req.(*DepositStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_PendingCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).PendingCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/PendingCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).PendingCommands(ctx, req.(*PendingCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Chains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Chains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/Chains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Chains(ctx, req.(*ChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_KeyAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).KeyAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/KeyAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).KeyAddress(ctx, req.(*KeyAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GatewayAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GatewayAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/GatewayAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GatewayAddress(ctx, req.(*GatewayAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Bytecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Bytecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/Bytecode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Bytecode(ctx, req.(*BytecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axelar.evm.v1beta1.QueryService/Event",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Event(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "axelar.evm.v1beta1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchedCommands",
			Handler:    _QueryService_BatchedCommands_Handler,
		},
		{
			MethodName: "BurnerInfo",
			Handler:    _QueryService_BurnerInfo_Handler,
		},
		{
			MethodName: "ConfirmationHeight",
			Handler:    _QueryService_ConfirmationHeight_Handler,
		},
		{
			MethodName: "DepositState",
			Handler:    _QueryService_DepositState_Handler,
		},
		{
			MethodName: "PendingCommands",
			Handler:    _QueryService_PendingCommands_Handler,
		},
		{
			MethodName: "Chains",
			Handler:    _QueryService_Chains_Handler,
		},
		{
			MethodName: "KeyAddress",
			Handler:    _QueryService_KeyAddress_Handler,
		},
		{
			MethodName: "GatewayAddress",
			Handler:    _QueryService_GatewayAddress_Handler,
		},
		{
			MethodName: "Bytecode",
			Handler:    _QueryService_Bytecode_Handler,
		},
		{
			MethodName: "Event",
			Handler:    _QueryService_Event_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "axelar/evm/v1beta1/service.proto",
}
